# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: "nodejs:12"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mydatabase:mongodb"

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: |
      export DB_USER="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r '.database[0].username')"
      export DB_PORT="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r '.database[0].port')"
      export MONGO_URL="mongodb://$DBUSER:$password@database.internal:$PORT"
      cd $PLATFORM_APP_DIR/front-end
      npm install
      npm run build
      cd $PLATFORM_APP_DIR/backend-end
      npm install
      npm run build
    # Deploy hooks can access services but the file system is now read-only.
    deploy: |


# The size of the persistent disk of the application (in MB).
disk: 512

# The 'mounts' describe writable, persistent filesystem mounts in the application.
# The keys are directory paths relative to the application root. The values are
# strings such as 'shared:files/NAME' where NAME is just a unique name for the mount.
mounts:
  "/run": "shared:files/run"

# The configuration of the application when it is exposed to the web.
web:
    commands:
      start: |
        export DB_HOST=`echo $PLATFORM_RELATIONSHIPS|base64 -d|jq -r ".database[0].host"`
        export DB_PASS=`echo $PLATFORM_RELATIONSHIPS|base64 -d|jq -r ".database[0].password"`
        export DB_USER=`echo $PLATFORM_RELATIONSHIPS|base64 -d|jq -r ".database[0].username"`
        export DB_PATH=`echo $PLATFORM_RELATIONSHIPS|base64 -d|jq -r ".database[0].path"`
        export DB_PORT=`echo $PLATFORM_RELATIONSHIPS|base64 -d|jq -r ".database[0].port"`
        export MONGO_URL="mongodb://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_PATH"
        node backend/dist/main
    locations:
      "/public":
        passthru: false
        root: "public"
        # Whether to allow files not matching a rule or not.
        allow: true
        rules:
          '\.png$':
            allow: true
            expires: -1
